py-flask/app/__init__.py
from flask import Flask
from secrets import token_hex


def create_app() -> Flask:
    app: Flask = Flask(__name__)
    app.config["SECRET_KEY"] = token_hex(16)
    
    from .views import views
    app.register_blueprint(views)
    
    return app

py-flask/app/views.py
# Import required libraries
from app.utils import *
from typing import Literal, Mapping, Union
from flask import Blueprint, render_template, redirect, url_for, request, Response


# Blueprint Object
views: Blueprint = Blueprint('views', __name__)


# Creating URLConf
@views.get("/")
def index() -> tuple[str, Literal[200]]: 
    return render_template("index.html", title="Home Page")


@views.get("/login")
def login() -> tuple[str, Literal[200]]:
    return render_template("data.html", data=import_data(), title="User Info ℹ️")


@views.post("/signup")
def signup() -> Response:    
    data: Mapping[str, Union[str, int]] = dict(
        zip(
            model,
            [
                request.form.get("name"), 
                int(request.form.get("age")), 
                request.form.get("reg_no"), 
                request.form.get("email"), 
                request.form.get("password")
            ]
        )
    )
    
    export_data(data)
    return redirect(url_for('views.login'))
    

py-flask/app/templates/data.html
{% extends "layout.html" %}


{% block body %}
<section class="center">
    <table>
        {% for key, value in data.items() %}
            <tr>
                <th>{{ key }}</th>
                <td>{{ value }}</td>
            </tr>
        {% endfor %}
    </table>        
</section>
{% endblock body %}

py-flask/app/templates/index.html
{% extends "layout.html" %}

{% block body %}
<section class="center">
    <form action="{{ url_for('views.signup') }}" method="post">
        <input type="text" value="Anonymous" name="name" placeholder="Full Name" required>
        <input type="number" value="20" name="age" min="18" max="25" step="1" placeholder="Age" required>
        <input type="text" value="10023478GD" name="reg_no" placeholder="Registration Number" required>
        <input type="email" value="test@gmail.com" name="email" placeholder="Email Address" required>
        <input type="password" value="5550123" name="password" placeholder="Password" required>
        <input type="submit">
    </form>
</section>
{% endblock body %}

py-flask/app/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    {% if title %}
        <title>{{ title }}</title>
    {% else %}
        <title>Hello, World 🌍</title>
    {% endif %}

    <style>
        body {
            text-align: center;
            font-family: Arial, sans-serif;
            margin-top: 2rem;
            background-color: snow;
        }

        section {
            height: fit-content;
        }

        form {
            display: flex;
            flex-wrap: wrap;
            flex-direction: column;
            margin: auto;
            width: 75%;
            text-align: center;
            padding: 10px;
            border: 1px solid teal;
            border-radius: 15px;
            box-shadow: 3px 4px 10px 3px lightgray;
        }

        input {
            text-align: center;
            font-style: italic;
            color: crimson;
            border: .5px dotted gold;
            padding: 5px;
            border-radius: 5px;
            width: 50%;
            margin: auto;
            margin-top: .5rem;
            margin-bottom: .5rem;
        }

        input[type="submit"] {
            width: fit-content;
            padding: 5px;
            margin: auto;
            font-weight: bolder;
            background-color: snow;
            margin-top: 1rem;
            margin-bottom: 1rem;
        }

        table {
            width: 75%;
            box-shadow: 3px 4px 10px 3px lightgray;
            padding: 5px;
            margin: auto;
            border: 1px solid teal;
            border-radius: 15px;
            font-style: italic;
        }

        th, td {
            padding: 10px;
            color: burlywood;
            font-weight: bolder;
        }

        .center {
            position: absolute;
            top: 50%;
            left: 50%;
            transform: translate(-50%, -50%);
            width: 50%;
        }
    </style>      
</head>
<body>
    {% block body %}{% endblock body %}
</body>
</html>